# Generated by Django 4.0.1 on 2022-01-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('part1', models.CharField(max_length=100)),
                ('part2', models.CharField(max_length=100)),
                ('isLearnt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.IntegerField()),
                ('word_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('set_id', 'word_id')},
            },
        ),
    ]
